import { Injectable, Logger } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';
import { PrismaService } from '../prisma/prisma.service';
import { ReceiptPdfService } from '../pdf/receipt-pdf.service';
import { R2UploadService } from '../common/services/r2-upload.service';
import { WhatsAppService } from '../whatsapp/whatsapp.service';
import { WhatsAppSettingsService } from '../whatsapp/whatsapp-settings.service';
import { paymentReceivedTemplate } from '../whatsapp/templates';
import { PAYMENT_RECEIVED } from './invoice-events';
import type { PaymentReceivedPayload } from './invoice-events';
import { resolveWhatsAppPhone } from '../common/utils/whatsapp-phone.util';

// Fires after a payment is confirmed — either at invoice creation (counter
// cash/UPI/card) or when a Razorpay QR payment is reconciled via webhook.
//
// Counter case: pdfUrl is the invoice PDF already generated by
//   InvoiceCreatedListener (shows Amount Paid, no Balance Due row).
// Razorpay case: pdfUrl is absent — we generate a compact A5 receipt PDF
//   via ReceiptPdfService and upload it to R2 before sending.
@Injectable()
export class PaymentReceivedListener {
  private readonly logger = new Logger(PaymentReceivedListener.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly receiptPdf: ReceiptPdfService,
    private readonly r2: R2UploadService,
    private readonly whatsapp: WhatsAppService,
    private readonly whatsappSettings: WhatsAppSettingsService,
  ) {}

  @OnEvent(PAYMENT_RECEIVED, { async: true })
  async handle(payload: PaymentReceivedPayload) {
    if (!(await this.whatsappSettings.isEnabled('paymentReceipt'))) return;

    const invoice = await this.prisma.invoice.findUnique({
      where: { id: payload.invoiceId },
      include: { customer: true, branch: true },
    });
    if (!invoice) {
      this.logger.warn(`payment-received: invoice ${payload.invoiceId} not found`);
      return;
    }

    const customer = invoice.customer;
    if (!customer?.whatsappOptIn) {
      this.logger.log(`payment-received: customer opted out or missing — ${payload.invoiceId}`);
      return;
    }
    const phone = resolveWhatsAppPhone(customer);
    if (!phone) return;

    // Resolve the PDF to attach. Counter sales pass the already-generated
    // invoice PDF URL; Razorpay payments generate a compact receipt PDF here.
    let pdfUrl = payload.pdfUrl ?? null;
    if (!pdfUrl) {
      try {
        const remaining = Number(invoice.grandTotal) - Number(invoice.amountPaid);
        const buf = await this.receiptPdf.render({
          receiptNumber: payload.receiptNumber,
          invoiceNumber: invoice.invoiceNumber,
          date: invoice.date,
          customerName: invoice.customerName,
          amount: payload.amount,
          paymentMode: payload.paymentMode,
          referenceNumber: payload.referenceNumber ?? null,
          branchName: invoice.branch?.name ?? null,
          remainingOutstanding: remaining > 0.01 ? remaining : 0,
        });
        const key = `receipts/${invoice.id}/${payload.receiptNumber}.pdf`;
        pdfUrl = await this.r2.upload({ buffer: buf, key, contentType: 'application/pdf' });
      } catch (e: any) {
        this.logger.error(
          `receipt PDF generation failed for ${payload.invoiceId}: ${e?.message ?? e}`,
        );
        return;
      }
    }

    try {
      const customerFirstName = (customer.name ?? 'Customer').split(/\s+/)[0];
      await this.whatsapp.sendTemplate({
        to: phone,
        template: paymentReceivedTemplate({
          customerFirstName,
          amount: payload.amount.toFixed(2),
          invoiceNumber: invoice.invoiceNumber,
          receiptNumber: payload.receiptNumber,
          pdfUrl,
        }),
        templateName: 'payment_received',
        mediaUrl: pdfUrl,
        bodySnapshot: `Payment received ₹${payload.amount.toFixed(2)} for ${invoice.invoiceNumber}`,
        relatedEntityType: 'invoice',
        relatedEntityId: invoice.id,
        branchId: invoice.branchId,
      });
    } catch (e: any) {
      this.logger.error(
        `payment_received WhatsApp send failed for ${payload.invoiceId}: ${e?.message ?? e}`,
      );
    }
  }
}
