import {
  Controller,
  Post,
  Body,
  UploadedFile,
  UseInterceptors,
  UseGuards,
  ParseFilePipe,
  MaxFileSizeValidator,
  FileTypeValidator,
  Request,
  Logger,
  InternalServerErrorException,
} from '@nestjs/common'
import { FileInterceptor } from '@nestjs/platform-express'
import { memoryStorage } from 'multer'
import { v4 as uuidv4 } from 'uuid'
import { SharedFilesService } from './shared-files.service'
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard'

// memoryStorage: file lands in `file.buffer` rather than on disk. We stream
// the buffer straight to R2 — no temp file ever touches the backend filesystem.
const multerOptions = { storage: memoryStorage() }

const DEFAULT_EXPIRES_IN_DAYS = 90
const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10 MB — generous for invoice PDFs

@Controller('api/v1/shared-files')
@UseGuards(JwtAuthGuard)
export class SharedFilesController {
  private readonly logger = new Logger(SharedFilesController.name)

  constructor(private readonly svc: SharedFilesService) {}

  @Post()
  @UseInterceptors(FileInterceptor('file', multerOptions))
  async upload(
    @UploadedFile(
      new ParseFilePipe({
        validators: [
          new MaxFileSizeValidator({ maxSize: MAX_FILE_SIZE }),
          // Skip magic-byte sniffing: the endpoint is auth-protected and the
          // PDFs are generated by our own frontend, so UUID + auth is enough.
          new FileTypeValidator({ fileType: 'application/pdf', skipMagicNumbersValidation: true }),
        ],
      }),
    )
    file: Express.Multer.File,
    @Request() req: any,
    @Body('label') label?: string,
    @Body('expiresInDays') expiresInDays?: string,
  ) {
    const id = uuidv4()
    const ttlDays = parseExpiresInDays(expiresInDays)
    // file.originalname is what the frontend named the File (e.g.
    // `Quotation-QTN-26-27-00002.pdf`). It becomes the URL's last segment
    // AND the saved-as filename on the customer's device.
    const filename = file.originalname || `${id}.pdf`

    try {
      // 1. Stream the buffer to R2 first. If R2 fails, we don't leave a
      //    DB row pointing at a missing object.
      await this.svc.upload(file.buffer, id, filename, file.mimetype || 'application/pdf')

      // 2. Persist the audit/cleanup row.
      const row = await this.svc.register({
        id,
        filename,
        mimeType: file.mimetype,
        sizeBytes: file.size,
        label,
        createdById: req.user.userId, // jwt.strategy emits `userId`, not `id`
        expiresInDays: ttlDays,
      })

      return {
        id: row.id,
        url: this.svc.buildUrl(row.id, row.filename),
        expiresAt: row.expiresAt,
      }
    } catch (err) {
      this.logger.error(
        `Failed to upload shared file: ${(err as Error).message}`,
        (err as Error).stack,
      )
      throw new InternalServerErrorException((err as Error).message)
    }
  }
}

function parseExpiresInDays(raw: string | undefined): number {
  if (!raw) return DEFAULT_EXPIRES_IN_DAYS
  const n = parseInt(raw, 10)
  if (!Number.isFinite(n) || n < 1 || n > 365) return DEFAULT_EXPIRES_IN_DAYS
  return n
}
